# Generated by Django 6.0.5 on 2026-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('chef', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_img', models.CharField(blank=True, max_length=500, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
            ],
        ),
    ]
