# Generated by Django 6.0.5 on 2026-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chef_img',
            new_name='chef_img_legacy',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='chef',
            new_name='chef_name_legacy',
        ),
    ]
