# Generated by Django 6.0.5 on 2026-05-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_chef_img_recipe_chef_img_legacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('specialty', models.CharField(max_length=200)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('facts', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.chef'),
        ),
    ]
